//Scrollbar
(function($){var methods={init:function(options){var defaults={set_width:false,set_height:false,horizontalScroll:false,scrollInertia:950,mouseWheel:true,mouseWheelPixels:"auto",autoDraggerLength:true,autoHideScrollbar:false,snapAmount:null,snapOffset:0,scrollButtons:{enable:false,scrollType:"continuous",scrollSpeed:"auto",scrollAmount:40},advanced:{updateOnBrowserResize:true,updateOnContentResize:false,autoExpandHorizontalScroll:false,autoScrollOnFocus:true,normalizeMouseWheelDelta:false},contentTouchScroll:true,callbacks:{onScrollStart:function(){},onScroll:function(){},onTotalScroll:function(){},onTotalScrollBack:function(){},onTotalScrollOffset:0,onTotalScrollBackOffset:0,whileScrolling:function(){}},theme:"dark-thin"},options=$.extend(true,defaults,options);return this.each(function(){var $this=$(this);if(options.set_width){$this.css("width",options.set_width);}
if(options.set_height){$this.css("height",options.set_height);}
if(!$(document).data("mCustomScrollbar-index")){$(document).data("mCustomScrollbar-index","1");}else{var mCustomScrollbarIndex=parseInt($(document).data("mCustomScrollbar-index"));$(document).data("mCustomScrollbar-index",mCustomScrollbarIndex+1);}
$this.wrapInner("<div class='mCustomScrollBox"+" mCS-"+options.theme+"' id='mCSB_"+$(document).data("mCustomScrollbar-index")+"' style='position:relative; height:100%; overflow:hidden; max-width:100%;' />").addClass("mCustomScrollbar _mCS_"+$(document).data("mCustomScrollbar-index"));var mCustomScrollBox=$this.children(".mCustomScrollBox");if(options.horizontalScroll){mCustomScrollBox.addClass("mCSB_horizontal").wrapInner("<div class='mCSB_h_wrapper' style='position:relative; left:0; width:999999px;' />");var mCSB_h_wrapper=mCustomScrollBox.children(".mCSB_h_wrapper");mCSB_h_wrapper.wrapInner("<div class='mCSB_container' style='position:absolute; left:0;' />").children(".mCSB_container").css({"width":mCSB_h_wrapper.children().outerWidth(),"position":"relative"}).unwrap();}else{mCustomScrollBox.wrapInner("<div class='mCSB_container' style='position:relative; top:0;' />");}
var mCSB_container=mCustomScrollBox.children(".mCSB_container");if($.support.touch){mCSB_container.addClass("mCS_touch");}
mCSB_container.after("<div class='mCSB_scrollTools' style='position:absolute;'><div class='mCSB_draggerContainer'><div class='mCSB_dragger' style='position:absolute;' oncontextmenu='return false;'><div class='mCSB_dragger_bar' style='position:relative;'></div></div><div class='mCSB_draggerRail'></div></div></div>");var mCSB_scrollTools=mCustomScrollBox.children(".mCSB_scrollTools"),mCSB_draggerContainer=mCSB_scrollTools.children(".mCSB_draggerContainer"),mCSB_dragger=mCSB_draggerContainer.children(".mCSB_dragger");if(options.horizontalScroll){mCSB_dragger.data("minDraggerWidth",mCSB_dragger.width());}else{mCSB_dragger.data("minDraggerHeight",mCSB_dragger.height());}
if(options.scrollButtons.enable){if(options.horizontalScroll){mCSB_scrollTools.prepend("<a class='mCSB_buttonLeft' oncontextmenu='return false;'></a>").append("<a class='mCSB_buttonRight' oncontextmenu='return false;'></a>");}else{mCSB_scrollTools.prepend("<a class='mCSB_buttonUp' oncontextmenu='return false;'></a>").append("<a class='mCSB_buttonDown' oncontextmenu='return false;'></a>");}}
mCustomScrollBox.bind("scroll",function(){if(!$this.is(".mCS_disabled")){mCustomScrollBox.scrollTop(0).scrollLeft(0);}});$this.data({"mCS_Init":true,"mCustomScrollbarIndex":$(document).data("mCustomScrollbar-index"),"horizontalScroll":options.horizontalScroll,"scrollInertia":options.scrollInertia,"scrollEasing":"mcsEaseOut","mouseWheel":options.mouseWheel,"mouseWheelPixels":options.mouseWheelPixels,"autoDraggerLength":options.autoDraggerLength,"autoHideScrollbar":options.autoHideScrollbar,"snapAmount":options.snapAmount,"snapOffset":options.snapOffset,"scrollButtons_enable":options.scrollButtons.enable,"scrollButtons_scrollType":options.scrollButtons.scrollType,"scrollButtons_scrollSpeed":options.scrollButtons.scrollSpeed,"scrollButtons_scrollAmount":options.scrollButtons.scrollAmount,"autoExpandHorizontalScroll":options.advanced.autoExpandHorizontalScroll,"autoScrollOnFocus":options.advanced.autoScrollOnFocus,"normalizeMouseWheelDelta":options.advanced.normalizeMouseWheelDelta,"contentTouchScroll":options.contentTouchScroll,"onScrollStart_Callback":options.callbacks.onScrollStart,"onScroll_Callback":options.callbacks.onScroll,"onTotalScroll_Callback":options.callbacks.onTotalScroll,"onTotalScrollBack_Callback":options.callbacks.onTotalScrollBack,"onTotalScroll_Offset":options.callbacks.onTotalScrollOffset,"onTotalScrollBack_Offset":options.callbacks.onTotalScrollBackOffset,"whileScrolling_Callback":options.callbacks.whileScrolling,"bindEvent_scrollbar_drag":false,"bindEvent_content_touch":false,"bindEvent_scrollbar_click":false,"bindEvent_mousewheel":false,"bindEvent_buttonsContinuous_y":false,"bindEvent_buttonsContinuous_x":false,"bindEvent_buttonsPixels_y":false,"bindEvent_buttonsPixels_x":false,"bindEvent_focusin":false,"bindEvent_autoHideScrollbar":false,"mCSB_buttonScrollRight":false,"mCSB_buttonScrollLeft":false,"mCSB_buttonScrollDown":false,"mCSB_buttonScrollUp":false});if(options.horizontalScroll){if($this.css("max-width")!=="none"){if(!options.advanced.updateOnContentResize){options.advanced.updateOnContentResize=true;}}}else{if($this.css("max-height")!=="none"){var percentage=false,maxHeight=parseInt($this.css("max-height"));if($this.css("max-height").indexOf("%")>=0){percentage=maxHeight,maxHeight=$this.parent().height()*percentage/100;}
$this.css("overflow","hidden");mCustomScrollBox.css("max-height",maxHeight);}}
$this.mCustomScrollbar("update");if(options.advanced.updateOnBrowserResize){var mCSB_resizeTimeout,currWinWidth=$(window).width(),currWinHeight=$(window).height();$(window).bind("resize."+$this.data("mCustomScrollbarIndex"),function(){if(mCSB_resizeTimeout){clearTimeout(mCSB_resizeTimeout);}
mCSB_resizeTimeout=setTimeout(function(){if(!$this.is(".mCS_disabled")&&!$this.is(".mCS_destroyed")){var winWidth=$(window).width(),winHeight=$(window).height();if(currWinWidth!==winWidth||currWinHeight!==winHeight){if($this.css("max-height")!=="none"&&percentage){mCustomScrollBox.css("max-height",$this.parent().height()*percentage/100);}
$this.mCustomScrollbar("update");currWinWidth=winWidth;currWinHeight=winHeight;}}},150);});}
if(options.advanced.updateOnContentResize){var mCSB_onContentResize;if(options.horizontalScroll){var mCSB_containerOldSize=mCSB_container.outerWidth();}else{var mCSB_containerOldSize=mCSB_container.outerHeight();}
mCSB_onContentResize=setInterval(function(){if(options.horizontalScroll){if(options.advanced.autoExpandHorizontalScroll){mCSB_container.css({"position":"absolute","width":"auto"}).wrap("<div class='mCSB_h_wrapper' style='position:relative; left:0; width:999999px;' />").css({"width":mCSB_container.outerWidth(),"position":"relative"}).unwrap();}
var mCSB_containerNewSize=mCSB_container.outerWidth();}else{var mCSB_containerNewSize=mCSB_container.outerHeight();}
if(mCSB_containerNewSize!=mCSB_containerOldSize){$this.mCustomScrollbar("update");mCSB_containerOldSize=mCSB_containerNewSize;}},300);}});},update:function(){var $this=$(this),mCustomScrollBox=$this.children(".mCustomScrollBox"),mCSB_container=mCustomScrollBox.children(".mCSB_container");mCSB_container.removeClass("mCS_no_scrollbar");$this.removeClass("mCS_disabled mCS_destroyed");mCustomScrollBox.scrollTop(0).scrollLeft(0);var mCSB_scrollTools=mCustomScrollBox.children(".mCSB_scrollTools"),mCSB_draggerContainer=mCSB_scrollTools.children(".mCSB_draggerContainer"),mCSB_dragger=mCSB_draggerContainer.children(".mCSB_dragger");if($this.data("horizontalScroll")){var mCSB_buttonLeft=mCSB_scrollTools.children(".mCSB_buttonLeft"),mCSB_buttonRight=mCSB_scrollTools.children(".mCSB_buttonRight"),mCustomScrollBoxW=mCustomScrollBox.width();if($this.data("autoExpandHorizontalScroll")){mCSB_container.css({"position":"absolute","width":"auto"}).wrap("<div class='mCSB_h_wrapper' style='position:relative; left:0; width:999999px;' />").css({"width":mCSB_container.outerWidth(),"position":"relative"}).unwrap();}
var mCSB_containerW=mCSB_container.outerWidth();}else{var mCSB_buttonUp=mCSB_scrollTools.children(".mCSB_buttonUp"),mCSB_buttonDown=mCSB_scrollTools.children(".mCSB_buttonDown"),mCustomScrollBoxH=mCustomScrollBox.height(),mCSB_containerH=mCSB_container.outerHeight();}
if(mCSB_containerH>mCustomScrollBoxH&&!$this.data("horizontalScroll")){mCSB_scrollTools.css("display","block");var mCSB_draggerContainerH=mCSB_draggerContainer.height();if($this.data("autoDraggerLength")){var draggerH=Math.round(mCustomScrollBoxH/mCSB_containerH*mCSB_draggerContainerH),minDraggerH=mCSB_dragger.data("minDraggerHeight");if(draggerH<=minDraggerH){mCSB_dragger.css({"height":minDraggerH});}else if(draggerH>=mCSB_draggerContainerH-10){var mCSB_draggerContainerMaxH=mCSB_draggerContainerH-10;mCSB_dragger.css({"height":mCSB_draggerContainerMaxH});}else{mCSB_dragger.css({"height":draggerH});}
mCSB_dragger.children(".mCSB_dragger_bar").css({"line-height":mCSB_dragger.height()+"px"});}
var mCSB_draggerH=mCSB_dragger.height(),scrollAmount=(mCSB_containerH-mCustomScrollBoxH)/(mCSB_draggerContainerH-mCSB_draggerH);$this.data("scrollAmount",scrollAmount).mCustomScrollbar("scrolling",mCustomScrollBox,mCSB_container,mCSB_draggerContainer,mCSB_dragger,mCSB_buttonUp,mCSB_buttonDown,mCSB_buttonLeft,mCSB_buttonRight);var mCSB_containerP=Math.abs(mCSB_container.position().top);$this.mCustomScrollbar("scrollTo",mCSB_containerP,{scrollInertia:0,trigger:"internal"});}else if(mCSB_containerW>mCustomScrollBoxW&&$this.data("horizontalScroll")){mCSB_scrollTools.css("display","block");var mCSB_draggerContainerW=mCSB_draggerContainer.width();if($this.data("autoDraggerLength")){var draggerW=Math.round(mCustomScrollBoxW/mCSB_containerW*mCSB_draggerContainerW),minDraggerW=mCSB_dragger.data("minDraggerWidth");if(draggerW<=minDraggerW){mCSB_dragger.css({"width":minDraggerW});}else if(draggerW>=mCSB_draggerContainerW-10){var mCSB_draggerContainerMaxW=mCSB_draggerContainerW-10;mCSB_dragger.css({"width":mCSB_draggerContainerMaxW});}else{mCSB_dragger.css({"width":draggerW});}}
var mCSB_draggerW=mCSB_dragger.width(),scrollAmount=(mCSB_containerW-mCustomScrollBoxW)/(mCSB_draggerContainerW-mCSB_draggerW);$this.data("scrollAmount",scrollAmount).mCustomScrollbar("scrolling",mCustomScrollBox,mCSB_container,mCSB_draggerContainer,mCSB_dragger,mCSB_buttonUp,mCSB_buttonDown,mCSB_buttonLeft,mCSB_buttonRight);var mCSB_containerP=Math.abs(mCSB_container.position().left);$this.mCustomScrollbar("scrollTo",mCSB_containerP,{scrollInertia:0,trigger:"internal"});}else{mCustomScrollBox.unbind("mousewheel focusin");if($this.data("horizontalScroll")){mCSB_dragger.add(mCSB_container).css("left",0);}else{mCSB_dragger.add(mCSB_container).css("top",0);}
mCSB_scrollTools.css("display","none");mCSB_container.addClass("mCS_no_scrollbar");$this.data({"bindEvent_mousewheel":false,"bindEvent_focusin":false});}},scrolling:function(mCustomScrollBox,mCSB_container,mCSB_draggerContainer,mCSB_dragger,mCSB_buttonUp,mCSB_buttonDown,mCSB_buttonLeft,mCSB_buttonRight){var $this=$(this);if(!$this.data("bindEvent_scrollbar_drag")){var mCSB_draggerDragY,mCSB_draggerDragX;if($.support.msPointer){mCSB_dragger.bind("MSPointerDown",function(e){e.preventDefault();$this.data({"on_drag":true});mCSB_dragger.addClass("mCSB_dragger_onDrag");var elem=$(this),elemOffset=elem.offset(),x=e.originalEvent.pageX-elemOffset.left,y=e.originalEvent.pageY-elemOffset.top;if(x<elem.width()&&x>0&&y<elem.height()&&y>0){mCSB_draggerDragY=y;mCSB_draggerDragX=x;}});$(document).bind("MSPointerMove."+$this.data("mCustomScrollbarIndex"),function(e){e.preventDefault();if($this.data("on_drag")){var elem=mCSB_dragger,elemOffset=elem.offset(),x=e.originalEvent.pageX-elemOffset.left,y=e.originalEvent.pageY-elemOffset.top;scrollbarDrag(mCSB_draggerDragY,mCSB_draggerDragX,y,x);}}).bind("MSPointerUp."+$this.data("mCustomScrollbarIndex"),function(e){$this.data({"on_drag":false});mCSB_dragger.removeClass("mCSB_dragger_onDrag");});}else{mCSB_dragger.bind("mousedown touchstart",function(e){e.preventDefault();e.stopImmediatePropagation();var elem=$(this),elemOffset=elem.offset(),x,y;if(e.type==="touchstart"){var touch=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0];x=touch.pageX-elemOffset.left;y=touch.pageY-elemOffset.top;}else{$this.data({"on_drag":true});mCSB_dragger.addClass("mCSB_dragger_onDrag");x=e.pageX-elemOffset.left;y=e.pageY-elemOffset.top;}
if(x<elem.width()&&x>0&&y<elem.height()&&y>0){mCSB_draggerDragY=y;mCSB_draggerDragX=x;}}).bind("touchmove",function(e){e.preventDefault();e.stopImmediatePropagation();var touch=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0],elem=$(this),elemOffset=elem.offset(),x=touch.pageX-elemOffset.left,y=touch.pageY-elemOffset.top;scrollbarDrag(mCSB_draggerDragY,mCSB_draggerDragX,y,x);});$(document).bind("mousemove."+$this.data("mCustomScrollbarIndex"),function(e){if($this.data("on_drag")){var elem=mCSB_dragger,elemOffset=elem.offset(),x=e.pageX-elemOffset.left,y=e.pageY-elemOffset.top;scrollbarDrag(mCSB_draggerDragY,mCSB_draggerDragX,y,x);}}).bind("mouseup."+$this.data("mCustomScrollbarIndex"),function(e){$this.data({"on_drag":false});mCSB_dragger.removeClass("mCSB_dragger_onDrag");});}
$this.data({"bindEvent_scrollbar_drag":true});}
function scrollbarDrag(mCSB_draggerDragY,mCSB_draggerDragX,y,x){if($this.data("horizontalScroll")){$this.mCustomScrollbar("scrollTo",(mCSB_dragger.position().left-(mCSB_draggerDragX))+x,{moveDragger:true,trigger:"internal"});}else{$this.mCustomScrollbar("scrollTo",(mCSB_dragger.position().top-(mCSB_draggerDragY))+y,{moveDragger:true,trigger:"internal"});}}
if($.support.touch&&$this.data("contentTouchScroll")){if(!$this.data("bindEvent_content_touch")){var touch,elem,elemOffset,y,x,mCSB_containerTouchY,mCSB_containerTouchX;mCSB_container.bind("touchstart",function(e){e.stopImmediatePropagation();touch=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0];elem=$(this);elemOffset=elem.offset();x=touch.pageX-elemOffset.left;y=touch.pageY-elemOffset.top;mCSB_containerTouchY=y;mCSB_containerTouchX=x;});mCSB_container.bind("touchmove",function(e){e.preventDefault();e.stopImmediatePropagation();touch=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0];elem=$(this).parent();elemOffset=elem.offset();x=touch.pageX-elemOffset.left;y=touch.pageY-elemOffset.top;if($this.data("horizontalScroll")){$this.mCustomScrollbar("scrollTo",mCSB_containerTouchX-x,{trigger:"internal"});}else{$this.mCustomScrollbar("scrollTo",mCSB_containerTouchY-y,{trigger:"internal"});}});}}
if(!$this.data("bindEvent_scrollbar_click")){mCSB_draggerContainer.bind("click",function(e){var scrollToPos=(e.pageY-mCSB_draggerContainer.offset().top)*$this.data("scrollAmount"),target=$(e.target);if($this.data("horizontalScroll")){scrollToPos=(e.pageX-mCSB_draggerContainer.offset().left)*$this.data("scrollAmount");}
if(target.hasClass("mCSB_draggerContainer")||target.hasClass("mCSB_draggerRail")){$this.mCustomScrollbar("scrollTo",scrollToPos,{trigger:"internal",scrollEasing:"draggerRailEase"});}});$this.data({"bindEvent_scrollbar_click":true});}
if($this.data("mouseWheel")){if(!$this.data("bindEvent_mousewheel")){mCustomScrollBox.bind("mousewheel",function(e,delta){var scrollTo,mouseWheelPixels=$this.data("mouseWheelPixels"),absPos=Math.abs(mCSB_container.position().top),draggerPos=mCSB_dragger.position().top,limit=mCSB_draggerContainer.height()-mCSB_dragger.height();if($this.data("normalizeMouseWheelDelta")){if(delta<0){delta=-1;}else{delta=1;}}
if(mouseWheelPixels==="auto"){mouseWheelPixels=100+Math.round($this.data("scrollAmount")/2);}
if($this.data("horizontalScroll")){draggerPos=mCSB_dragger.position().left;limit=mCSB_draggerContainer.width()-mCSB_dragger.width();absPos=Math.abs(mCSB_container.position().left);}
if((delta>0&&draggerPos!==0)||(delta<0&&draggerPos!==limit)){e.preventDefault();e.stopImmediatePropagation();}
scrollTo=absPos-(delta*mouseWheelPixels);$this.mCustomScrollbar("scrollTo",scrollTo,{trigger:"internal"});});$this.data({"bindEvent_mousewheel":true});}}
if($this.data("scrollButtons_enable")){if($this.data("scrollButtons_scrollType")==="pixels"){if($this.data("horizontalScroll")){mCSB_buttonRight.add(mCSB_buttonLeft).unbind("mousedown touchstart MSPointerDown mouseup MSPointerUp mouseout MSPointerOut touchend",mCSB_buttonRight_stop,mCSB_buttonLeft_stop);$this.data({"bindEvent_buttonsContinuous_x":false});if(!$this.data("bindEvent_buttonsPixels_x")){mCSB_buttonRight.bind("click",function(e){e.preventDefault();PixelsScrollTo(Math.abs(mCSB_container.position().left)+$this.data("scrollButtons_scrollAmount"));});mCSB_buttonLeft.bind("click",function(e){e.preventDefault();PixelsScrollTo(Math.abs(mCSB_container.position().left)-$this.data("scrollButtons_scrollAmount"));});$this.data({"bindEvent_buttonsPixels_x":true});}}else{mCSB_buttonDown.add(mCSB_buttonUp).unbind("mousedown touchstart MSPointerDown mouseup MSPointerUp mouseout MSPointerOut touchend",mCSB_buttonRight_stop,mCSB_buttonLeft_stop);$this.data({"bindEvent_buttonsContinuous_y":false});if(!$this.data("bindEvent_buttonsPixels_y")){mCSB_buttonDown.bind("click",function(e){e.preventDefault();PixelsScrollTo(Math.abs(mCSB_container.position().top)+$this.data("scrollButtons_scrollAmount"));});mCSB_buttonUp.bind("click",function(e){e.preventDefault();PixelsScrollTo(Math.abs(mCSB_container.position().top)-$this.data("scrollButtons_scrollAmount"));});$this.data({"bindEvent_buttonsPixels_y":true});}}
function PixelsScrollTo(to){if(!mCSB_dragger.data("preventAction")){mCSB_dragger.data("preventAction",true);$this.mCustomScrollbar("scrollTo",to,{trigger:"internal"});}}}else{if($this.data("horizontalScroll")){mCSB_buttonRight.add(mCSB_buttonLeft).unbind("click");$this.data({"bindEvent_buttonsPixels_x":false});if(!$this.data("bindEvent_buttonsContinuous_x")){mCSB_buttonRight.bind("mousedown touchstart MSPointerDown",function(e){e.preventDefault();var scrollButtonsSpeed=ScrollButtonsSpeed();$this.data({"mCSB_buttonScrollRight":setInterval(function(){$this.mCustomScrollbar("scrollTo",Math.abs(mCSB_container.position().left)+scrollButtonsSpeed,{trigger:"internal",scrollEasing:"easeOutCirc"});},17)});});var mCSB_buttonRight_stop=function(e){e.preventDefault();clearInterval($this.data("mCSB_buttonScrollRight"));}
mCSB_buttonRight.bind("mouseup touchend MSPointerUp mouseout MSPointerOut",mCSB_buttonRight_stop);mCSB_buttonLeft.bind("mousedown touchstart MSPointerDown",function(e){e.preventDefault();var scrollButtonsSpeed=ScrollButtonsSpeed();$this.data({"mCSB_buttonScrollLeft":setInterval(function(){$this.mCustomScrollbar("scrollTo",Math.abs(mCSB_container.position().left)-scrollButtonsSpeed,{trigger:"internal",scrollEasing:"easeOutCirc"});},17)});});var mCSB_buttonLeft_stop=function(e){e.preventDefault();clearInterval($this.data("mCSB_buttonScrollLeft"));}
mCSB_buttonLeft.bind("mouseup touchend MSPointerUp mouseout MSPointerOut",mCSB_buttonLeft_stop);$this.data({"bindEvent_buttonsContinuous_x":true});}}else{mCSB_buttonDown.add(mCSB_buttonUp).unbind("click");$this.data({"bindEvent_buttonsPixels_y":false});if(!$this.data("bindEvent_buttonsContinuous_y")){mCSB_buttonDown.bind("mousedown touchstart MSPointerDown",function(e){e.preventDefault();var scrollButtonsSpeed=ScrollButtonsSpeed();$this.data({"mCSB_buttonScrollDown":setInterval(function(){$this.mCustomScrollbar("scrollTo",Math.abs(mCSB_container.position().top)+scrollButtonsSpeed,{trigger:"internal",scrollEasing:"easeOutCirc"});},17)});});var mCSB_buttonDown_stop=function(e){e.preventDefault();clearInterval($this.data("mCSB_buttonScrollDown"));}
mCSB_buttonDown.bind("mouseup touchend MSPointerUp mouseout MSPointerOut",mCSB_buttonDown_stop);mCSB_buttonUp.bind("mousedown touchstart MSPointerDown",function(e){e.preventDefault();var scrollButtonsSpeed=ScrollButtonsSpeed();$this.data({"mCSB_buttonScrollUp":setInterval(function(){$this.mCustomScrollbar("scrollTo",Math.abs(mCSB_container.position().top)-scrollButtonsSpeed,{trigger:"internal",scrollEasing:"easeOutCirc"});},17)});});var mCSB_buttonUp_stop=function(e){e.preventDefault();clearInterval($this.data("mCSB_buttonScrollUp"));}
mCSB_buttonUp.bind("mouseup touchend MSPointerUp mouseout MSPointerOut",mCSB_buttonUp_stop);$this.data({"bindEvent_buttonsContinuous_y":true});}}
function ScrollButtonsSpeed(){var speed=$this.data("scrollButtons_scrollSpeed");if($this.data("scrollButtons_scrollSpeed")==="auto"){speed=Math.round(($this.data("scrollInertia")+100)/40);}
return speed;}}}
if($this.data("autoScrollOnFocus")){if(!$this.data("bindEvent_focusin")){mCustomScrollBox.bind("focusin",function(){mCustomScrollBox.scrollTop(0).scrollLeft(0);var focusedElem=$(document.activeElement);if(focusedElem.is("input,textarea,select,button,a[tabindex],area,object")){var mCSB_containerPos=mCSB_container.position().top,focusedElemPos=focusedElem.position().top,visibleLimit=mCustomScrollBox.height()-focusedElem.outerHeight();if($this.data("horizontalScroll")){mCSB_containerPos=mCSB_container.position().left;focusedElemPos=focusedElem.position().left;visibleLimit=mCustomScrollBox.width()-focusedElem.outerWidth();}
if(mCSB_containerPos+focusedElemPos<0||mCSB_containerPos+focusedElemPos>visibleLimit){$this.mCustomScrollbar("scrollTo",focusedElemPos,{trigger:"internal"});}}});$this.data({"bindEvent_focusin":true});}}
if($this.data("autoHideScrollbar")){if(!$this.data("bindEvent_autoHideScrollbar")){mCustomScrollBox.bind("mouseenter",function(e){mCustomScrollBox.addClass("mCS-mouse-over");functions.showScrollbar.call(mCustomScrollBox.children(".mCSB_scrollTools"));}).bind("mouseleave touchend",function(e){mCustomScrollBox.removeClass("mCS-mouse-over");if(e.type==="mouseleave"){functions.hideScrollbar.call(mCustomScrollBox.children(".mCSB_scrollTools"));}});$this.data({"bindEvent_autoHideScrollbar":true});}}},scrollTo:function(scrollTo,options){var $this=$(this),defaults={moveDragger:false,trigger:"external",callbacks:true,scrollInertia:$this.data("scrollInertia"),scrollEasing:$this.data("scrollEasing")},options=$.extend(defaults,options),draggerScrollTo,mCustomScrollBox=$this.children(".mCustomScrollBox"),mCSB_container=mCustomScrollBox.children(".mCSB_container"),mCSB_scrollTools=mCustomScrollBox.children(".mCSB_scrollTools"),mCSB_draggerContainer=mCSB_scrollTools.children(".mCSB_draggerContainer"),mCSB_dragger=mCSB_draggerContainer.children(".mCSB_dragger"),contentSpeed=draggerSpeed=options.scrollInertia,scrollBeginning,scrollBeginningOffset,totalScroll,totalScrollOffset;if(!mCSB_container.hasClass("mCS_no_scrollbar")){$this.data({"mCS_trigger":options.trigger});if($this.data("mCS_Init")){options.callbacks=false;}
if(scrollTo||scrollTo===0){if(typeof(scrollTo)==="number"){if(options.moveDragger){draggerScrollTo=scrollTo;if($this.data("horizontalScroll")){scrollTo=mCSB_dragger.position().left*$this.data("scrollAmount");}else{scrollTo=mCSB_dragger.position().top*$this.data("scrollAmount");}
draggerSpeed=0;}else{draggerScrollTo=scrollTo/$this.data("scrollAmount");}}else if(typeof(scrollTo)==="string"){var target;if(scrollTo==="top"){target=0;}else if(scrollTo==="bottom"&&!$this.data("horizontalScroll")){target=mCSB_container.outerHeight()-mCustomScrollBox.height();}else if(scrollTo==="left"){target=0;}else if(scrollTo==="right"&&$this.data("horizontalScroll")){target=mCSB_container.outerWidth()-mCustomScrollBox.width();}else if(scrollTo==="first"){target=$this.find(".mCSB_container").find(":first");}else if(scrollTo==="last"){target=$this.find(".mCSB_container").find(":last");}else{target=$this.find(scrollTo);}
if(target.length===1){if($this.data("horizontalScroll")){scrollTo=target.position().left;}else{scrollTo=target.position().top;}
draggerScrollTo=scrollTo/$this.data("scrollAmount");}else{draggerScrollTo=scrollTo=target;}}
if($this.data("horizontalScroll")){if($this.data("onTotalScrollBack_Offset")){scrollBeginningOffset=-$this.data("onTotalScrollBack_Offset");}
if($this.data("onTotalScroll_Offset")){totalScrollOffset=mCustomScrollBox.width()-mCSB_container.outerWidth()+$this.data("onTotalScroll_Offset");}
if(draggerScrollTo<0){draggerScrollTo=scrollTo=0;clearInterval($this.data("mCSB_buttonScrollLeft"));if(!scrollBeginningOffset){scrollBeginning=true;}}else if(draggerScrollTo>=mCSB_draggerContainer.width()-mCSB_dragger.width()){draggerScrollTo=mCSB_draggerContainer.width()-mCSB_dragger.width();scrollTo=mCustomScrollBox.width()-mCSB_container.outerWidth();clearInterval($this.data("mCSB_buttonScrollRight"));if(!totalScrollOffset){totalScroll=true;}}else{scrollTo=-scrollTo;}
var snapAmount=$this.data("snapAmount");if(snapAmount){scrollTo=Math.round(scrollTo/snapAmount)*snapAmount-$this.data("snapOffset");}
functions.mTweenAxis.call(this,mCSB_dragger[0],"left",Math.round(draggerScrollTo),draggerSpeed,options.scrollEasing);functions.mTweenAxis.call(this,mCSB_container[0],"left",Math.round(scrollTo),contentSpeed,options.scrollEasing,{onStart:function(){if(options.callbacks&&!$this.data("mCS_tweenRunning")){callbacks("onScrollStart");}
if($this.data("autoHideScrollbar")){functions.showScrollbar.call(mCSB_scrollTools);}},onUpdate:function(){if(options.callbacks){callbacks("whileScrolling");}},onComplete:function(){if(options.callbacks){callbacks("onScroll");if(scrollBeginning||(scrollBeginningOffset&&mCSB_container.position().left>=scrollBeginningOffset)){callbacks("onTotalScrollBack");}
if(totalScroll||(totalScrollOffset&&mCSB_container.position().left<=totalScrollOffset)){callbacks("onTotalScroll");}}
mCSB_dragger.data("preventAction",false);$this.data("mCS_tweenRunning",false);if($this.data("autoHideScrollbar")){if(!mCustomScrollBox.hasClass("mCS-mouse-over")){functions.hideScrollbar.call(mCSB_scrollTools);}}}});}else{if($this.data("onTotalScrollBack_Offset")){scrollBeginningOffset=-$this.data("onTotalScrollBack_Offset");}
if($this.data("onTotalScroll_Offset")){totalScrollOffset=mCustomScrollBox.height()-mCSB_container.outerHeight()+$this.data("onTotalScroll_Offset");}
if(draggerScrollTo<0){draggerScrollTo=scrollTo=0;clearInterval($this.data("mCSB_buttonScrollUp"));if(!scrollBeginningOffset){scrollBeginning=true;}}else if(draggerScrollTo>=mCSB_draggerContainer.height()-mCSB_dragger.height()){draggerScrollTo=mCSB_draggerContainer.height()-mCSB_dragger.height();scrollTo=mCustomScrollBox.height()-mCSB_container.outerHeight();clearInterval($this.data("mCSB_buttonScrollDown"));if(!totalScrollOffset){totalScroll=true;}}else{scrollTo=-scrollTo;}
var snapAmount=$this.data("snapAmount");if(snapAmount){scrollTo=Math.round(scrollTo/snapAmount)*snapAmount-$this.data("snapOffset");}
functions.mTweenAxis.call(this,mCSB_dragger[0],"top",Math.round(draggerScrollTo),draggerSpeed,options.scrollEasing);functions.mTweenAxis.call(this,mCSB_container[0],"top",Math.round(scrollTo),contentSpeed,options.scrollEasing,{onStart:function(){if(options.callbacks&&!$this.data("mCS_tweenRunning")){callbacks("onScrollStart");}
if($this.data("autoHideScrollbar")){functions.showScrollbar.call(mCSB_scrollTools);}},onUpdate:function(){if(options.callbacks){callbacks("whileScrolling");}},onComplete:function(){if(options.callbacks){callbacks("onScroll");if(scrollBeginning||(scrollBeginningOffset&&mCSB_container.position().top>=scrollBeginningOffset)){callbacks("onTotalScrollBack");}
if(totalScroll||(totalScrollOffset&&mCSB_container.position().top<=totalScrollOffset)){callbacks("onTotalScroll");}}
mCSB_dragger.data("preventAction",false);$this.data("mCS_tweenRunning",false);if($this.data("autoHideScrollbar")){if(!mCustomScrollBox.hasClass("mCS-mouse-over")){functions.hideScrollbar.call(mCSB_scrollTools);}}}});}
if($this.data("mCS_Init")){$this.data({"mCS_Init":false});}}}
function callbacks(cb){this.mcs={top:mCSB_container.position().top,left:mCSB_container.position().left,draggerTop:mCSB_dragger.position().top,draggerLeft:mCSB_dragger.position().left,topPct:Math.round((100*Math.abs(mCSB_container.position().top))/Math.abs(mCSB_container.outerHeight()-mCustomScrollBox.height())),leftPct:Math.round((100*Math.abs(mCSB_container.position().left))/Math.abs(mCSB_container.outerWidth()-mCustomScrollBox.width()))};switch(cb){case"onScrollStart":$this.data("mCS_tweenRunning",true).data("onScrollStart_Callback").call($this,this.mcs);break;case"whileScrolling":$this.data("whileScrolling_Callback").call($this,this.mcs);break;case"onScroll":$this.data("onScroll_Callback").call($this,this.mcs);break;case"onTotalScrollBack":$this.data("onTotalScrollBack_Callback").call($this,this.mcs);break;case"onTotalScroll":$this.data("onTotalScroll_Callback").call($this,this.mcs);break;}}},stop:function(){var $this=$(this),mCSB_container=$this.children().children(".mCSB_container"),mCSB_dragger=$this.children().children().children().children(".mCSB_dragger");functions.mTweenAxisStop.call(this,mCSB_container[0]);functions.mTweenAxisStop.call(this,mCSB_dragger[0]);},disable:function(resetScroll){var $this=$(this),mCustomScrollBox=$this.children(".mCustomScrollBox"),mCSB_container=mCustomScrollBox.children(".mCSB_container"),mCSB_scrollTools=mCustomScrollBox.children(".mCSB_scrollTools"),mCSB_dragger=mCSB_scrollTools.children().children(".mCSB_dragger");mCustomScrollBox.unbind("mousewheel focusin mouseenter mouseleave touchend");mCSB_container.unbind("touchstart touchmove")
if(resetScroll){if($this.data("horizontalScroll")){mCSB_dragger.add(mCSB_container).css("left",0);}else{mCSB_dragger.add(mCSB_container).css("top",0);}}
mCSB_scrollTools.css("display","none");mCSB_container.addClass("mCS_no_scrollbar");$this.data({"bindEvent_mousewheel":false,"bindEvent_focusin":false,"bindEvent_content_touch":false,"bindEvent_autoHideScrollbar":false}).addClass("mCS_disabled");},destroy:function(){var $this=$(this);$this.removeClass("mCustomScrollbar _mCS_"+$this.data("mCustomScrollbarIndex")).addClass("mCS_destroyed").children().children(".mCSB_container").unwrap().children().unwrap().siblings(".mCSB_scrollTools").remove();$(document).unbind("mousemove."+$this.data("mCustomScrollbarIndex")+" mouseup."+$this.data("mCustomScrollbarIndex")+" MSPointerMove."+$this.data("mCustomScrollbarIndex")+" MSPointerUp."+$this.data("mCustomScrollbarIndex"));$(window).unbind("resize."+$this.data("mCustomScrollbarIndex"));}},functions={showScrollbar:function(){this.stop().animate({opacity:1},"fast");},hideScrollbar:function(){this.stop().animate({opacity:0},"fast");},mTweenAxis:function(el,prop,to,duration,easing,callbacks){var callbacks=callbacks||{},onStart=callbacks.onStart||function(){},onUpdate=callbacks.onUpdate||function(){},onComplete=callbacks.onComplete||function(){};var startTime=_getTime(),_delay,progress=0,from=el.offsetTop,elStyle=el.style;if(prop==="left"){from=el.offsetLeft;}
var diff=to-from;_cancelTween();_startTween();function _getTime(){if(window.performance&&window.performance.now){return window.performance.now();}else{if(window.performance&&window.performance.webkitNow){return window.performance.webkitNow();}else{if(Date.now){return Date.now();}else{return new Date().getTime();}}}}
function _step(){if(!progress){onStart.call();}
progress=_getTime()-startTime;_tween();if(progress>=el._time){el._time=(progress>el._time)?progress+_delay-(progress-el._time):progress+_delay-1;if(el._time<progress+1){el._time=progress+1;}}
if(el._time<duration){el._id=_request(_step);}else{onComplete.call();}}
function _tween(){if(duration>0){el.currVal=_ease(el._time,from,diff,duration,easing);elStyle[prop]=Math.round(el.currVal)+"px";}else{elStyle[prop]=to+"px";}
onUpdate.call();}
function _startTween(){_delay=1000/60;el._time=progress+_delay;_request=(!window.requestAnimationFrame)?function(f){_tween();return setTimeout(f,0.01);}:window.requestAnimationFrame;el._id=_request(_step);}
function _cancelTween(){if(el._id==null){return;}
if(!window.requestAnimationFrame){clearTimeout(el._id);}else{window.cancelAnimationFrame(el._id);}
el._id=null;}
function _ease(t,b,c,d,type){switch(type){case"linear":return c*t/d+b;break;case"easeOutQuad":t/=d;return-c*t*(t-2)+b;break;case"easeInOutQuad":t/=d/2;if(t<1)return c/2*t*t+b;t--;return-c/2*(t*(t-2)-1)+b;break;case"easeOutCubic":t/=d;t--;return c*(t*t*t+1)+b;break;case"easeOutQuart":t/=d;t--;return-c*(t*t*t*t-1)+b;break;case"easeOutQuint":t/=d;t--;return c*(t*t*t*t*t+1)+b;break;case"easeOutCirc":t/=d;t--;return c*Math.sqrt(1-t*t)+b;break;case"easeOutSine":return c*Math.sin(t/d*(Math.PI/2))+b;break;case"easeOutExpo":return c*(-Math.pow(2,-10*t/d)+1)+b;break;case"mcsEaseOut":var ts=(t/=d)*t,tc=ts*t;return b+c*(0.499999999999997*tc*ts+-2.5*ts*ts+5.5*tc+-6.5*ts+4*t);break;case"draggerRailEase":t/=d/2;if(t<1)return c/2*t*t*t+b;t-=2;return c/2*(t*t*t+2)+b;break;}}},mTweenAxisStop:function(el){if(el._id==null){return;}
if(!window.requestAnimationFrame){clearTimeout(el._id);}else{window.cancelAnimationFrame(el._id);}
el._id=null;},rafPolyfill:function(){var pfx=["ms","moz","webkit","o"],i=pfx.length;while(--i>-1&&!window.requestAnimationFrame){window.requestAnimationFrame=window[pfx[i]+"RequestAnimationFrame"];window.cancelAnimationFrame=window[pfx[i]+"CancelAnimationFrame"]||window[pfx[i]+"CancelRequestAnimationFrame"];}}}
functions.rafPolyfill.call();$.support.touch=!!('ontouchstart'in window);$.support.msPointer=window.navigator.msPointerEnabled;$.fn.mCustomScrollbar=function(method){if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method==="object"||!method){return methods.init.apply(this,arguments);}else{$.error("Method "+method+" does not exist");}};})(jQuery);
(function(a){function d(b){var c=b||window.event,d=[].slice.call(arguments,1),e=0,f=!0,g=0,h=0;return b=a.event.fix(c),b.type="mousewheel",c.wheelDelta&&(e=c.wheelDelta/120),c.detail&&(e=-c.detail/3),h=e,c.axis!==undefined&&c.axis===c.HORIZONTAL_AXIS&&(h=0,g=-1*e),c.wheelDeltaY!==undefined&&(h=c.wheelDeltaY/120),c.wheelDeltaX!==undefined&&(g=-1*c.wheelDeltaX/120),d.unshift(b,e,g,h),(a.event.dispatch||a.event.handle).apply(this,d)}var b=["DOMMouseScroll","mousewheel"];if(a.event.fixHooks)for(var c=b.length;c;)a.event.fixHooks[b[--c]]=a.event.mouseHooks;a.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=b.length;a;)this.addEventListener(b[--a],d,!1);else this.onmousewheel=d},teardown:function(){if(this.removeEventListener)for(var a=b.length;a;)this.removeEventListener(b[--a],d,!1);else this.onmousewheel=null}},a.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);$(".skrol1, .skrol2, .skrol3, .skrol4").mCustomScrollbar({ });
//Modal
(function(a){var c=null;a.modal=function(b,f){a.modal.close();var e,d;this.$body=a("body");this.options=a.extend({},a.modal.defaults,f);if(b.is("a"))if(d=b.attr("href"),/^#/.test(d)){this.$elm=a(d);if(1!==this.$elm.length)return null;this.open()}else this.$elm=a("<div>"),this.$body.append(this.$elm),e=function(a,b){b.elm.remove()},this.showSpinner(),b.trigger(a.modal.AJAX_SEND),a.get(d).done(function(d){c&&(b.trigger(a.modal.AJAX_SUCCESS),c.$elm.empty().append(d).on(a.modal.CLOSE,e),c.hideSpinner(),
c.open(),b.trigger(a.modal.AJAX_COMPLETE))}).fail(function(){b.trigger(a.modal.AJAX_FAIL);c.hideSpinner();b.trigger(a.modal.AJAX_COMPLETE)});else this.$elm=b,this.open()};a.modal.prototype={constructor:a.modal,open:function(){this.block();this.show();if(this.options.escapeClose)a(document).on("keydown.modal",function(b){27==b.which&&a.modal.close()});this.options.clickClose&&this.blocker.click(a.modal.close)},close:function(){this.unblock();this.hide();a(document).off("keydown.modal")},block:function(){this.$elm.trigger(a.modal.BEFORE_BLOCK,
[this._ctx()]);this.blocker=a('<div class="jquery-modal blocker"></div>').css({top:0,right:0,bottom:0,left:0,width:"100%",height:"100%",position:"fixed",zIndex:this.options.zIndex,background:this.options.overlay,opacity:this.options.opacity});this.$body.append(this.blocker);this.$elm.trigger(a.modal.BLOCK,[this._ctx()])},unblock:function(){this.blocker.remove()},show:function(){this.$elm.trigger(a.modal.BEFORE_OPEN,[this._ctx()]);this.options.showClose&&(this.closeButton=a('<a href="#close-modal" rel="modal:close" class="close-modal">'+
this.options.closeText+"</a>"),this.$elm.append(this.closeButton));this.$elm.addClass(this.options.modalClass+" current");this.center();this.$elm.show().trigger(a.modal.OPEN,[this._ctx()])},hide:function(){this.$elm.trigger(a.modal.BEFORE_CLOSE,[this._ctx()]);this.closeButton&&this.closeButton.remove();this.$elm.removeClass("current").hide();this.$elm.trigger(a.modal.CLOSE,[this._ctx()])},showSpinner:function(){this.options.showSpinner&&(this.spinner=this.spinner||a('<div class="'+this.options.modalClass+
'-spinner"></div>').append(this.options.spinnerHtml),this.$body.append(this.spinner),this.spinner.show())},hideSpinner:function(){this.spinner&&this.spinner.remove()},center:function(){this.$elm.css({position:"fixed",top:"50%",left:"50%",marginTop:-(this.$elm.outerHeight()/2),marginLeft:-(this.$elm.outerWidth()/2),zIndex:this.options.zIndex+1})},_ctx:function(){return{elm:this.$elm,blocker:this.blocker,options:this.options}}};a.modal.prototype.resize=a.modal.prototype.center;a.modal.close=function(a){if(c)return a&&
a.preventDefault(),c.close(),a=c.$elm,c=null,a};a.modal.resize=function(){c&&c.resize()};a.modal.defaults={overlay:"#000",opacity:0.75,zIndex:1,escapeClose:!0,clickClose:!0,closeText:"[X]",modalClass:"modal",spinnerHtml:null,showSpinner:!0,showClose:!0};a.modal.BEFORE_BLOCK="modal:before-block";a.modal.BLOCK="modal:block";a.modal.BEFORE_OPEN="modal:before-open";a.modal.OPEN="modal:open";a.modal.BEFORE_CLOSE="modal:before-close";a.modal.CLOSE="modal:close";a.modal.AJAX_SEND="modal:ajax:send";a.modal.AJAX_SUCCESS=
"modal:ajax:success";a.modal.AJAX_FAIL="modal:ajax:fail";a.modal.AJAX_COMPLETE="modal:ajax:complete";a.fn.modal=function(b){1===this.length&&(c=new a.modal(this,b));return this};a(document).on("click.modal",'a[rel="modal:close"]',a.modal.close);a(document).on("click.modal",'a[rel="modal:open"]',function(b){b.preventDefault();a(this).modal()})})(jQuery);
//Slider
(function($){$.flexslider=function(el,options){var slider=$(el),vars=$.extend({},$.flexslider.defaults,options),namespace=vars.namespace,touch=("ontouchstart"in window)||window.DocumentTouch&&document instanceof DocumentTouch,eventType=(touch)?"touchend":"click",vertical=vars.direction==="vertical",reverse=vars.reverse,carousel=(vars.itemWidth>0),fade=vars.animation==="fade",asNav=vars.asNavFor!=="",methods={};$.data(el,"flexslider",slider);methods={init:function(){slider.animating=false;slider.currentSlide=vars.startAt;slider.animatingTo=slider.currentSlide;slider.atEnd=(slider.currentSlide===0||slider.currentSlide===slider.last);slider.containerSelector=vars.selector.substr(0,vars.selector.search(' '));slider.slides=$(vars.selector,slider);slider.container=$(slider.containerSelector,slider);slider.count=slider.slides.length;slider.syncExists=$(vars.sync).length>0;if(vars.animation==="slide")vars.animation="swing";slider.prop=(vertical)?"top":"marginLeft";slider.args={};slider.manualPause=false;slider.transitions=!vars.video&&!fade&&vars.useCSS&&(function(){var obj=document.createElement('div'),props=['perspectiveProperty','WebkitPerspective','MozPerspective','OPerspective','msPerspective'];for(var i in props){if(obj.style[props[i]]!==undefined){slider.pfx=props[i].replace('Perspective','').toLowerCase();slider.prop="-"+slider.pfx+"-transform";return true;}}
return false;}());if(vars.controlsContainer!=="")slider.controlsContainer=$(vars.controlsContainer).length>0&&$(vars.controlsContainer);if(vars.manualControls!=="")slider.manualControls=$(vars.manualControls).length>0&&$(vars.manualControls);if(vars.randomize){slider.slides.sort(function(){return(Math.round(Math.random())-0.5);});slider.container.empty().append(slider.slides);}
slider.doMath();if(asNav)methods.asNav.setup();slider.setup("init");if(vars.controlNav)methods.controlNav.setup();if(vars.directionNav)methods.directionNav.setup();if(vars.keyboard&&($(slider.containerSelector).length===1||vars.multipleKeyboard)){$(document).bind('keyup',function(event){var keycode=event.keyCode;if(!slider.animating&&(keycode===39||keycode===37)){var target=(keycode===39)?slider.getTarget('next'):(keycode===37)?slider.getTarget('prev'):false;slider.flexAnimate(target,vars.pauseOnAction);}});}
if(vars.mousewheel){slider.bind('mousewheel',function(event,delta,deltaX,deltaY){event.preventDefault();var target=(delta<0)?slider.getTarget('next'):slider.getTarget('prev');slider.flexAnimate(target,vars.pauseOnAction);});}
if(vars.pausePlay)methods.pausePlay.setup();if(vars.slideshow){if(vars.pauseOnHover){slider.hover(function(){if(!slider.manualPlay&&!slider.manualPause)slider.pause();},function(){if(!slider.manualPause&&!slider.manualPlay)slider.play();});}
(vars.initDelay>0)?setTimeout(slider.play,vars.initDelay):slider.play();}
if(touch&&vars.touch)methods.touch();if(!fade||(fade&&vars.smoothHeight))$(window).bind("resize focus",methods.resize);setTimeout(function(){vars.start(slider);},200);},asNav:{setup:function(){slider.asNav=true;slider.animatingTo=Math.floor(slider.currentSlide/slider.move);slider.currentItem=slider.currentSlide;slider.slides.removeClass(namespace+"active-slide").eq(slider.currentItem).addClass(namespace+"active-slide");slider.slides.click(function(e){e.preventDefault();var $slide=$(this),target=$slide.index();if(!$(vars.asNavFor).data('flexslider').animating&&!$slide.hasClass('active')){slider.direction=(slider.currentItem<target)?"next":"prev";slider.flexAnimate(target,vars.pauseOnAction,false,true,true);}});}},controlNav:{setup:function(){if(!slider.manualControls){methods.controlNav.setupPaging();}else{methods.controlNav.setupManual();}},setupPaging:function(){var type=(vars.controlNav==="thumbnails")?'control-thumbs':'control-paging',j=1,item;slider.controlNavScaffold=$('<ol class="'+namespace+'control-nav '+namespace+type+'"></ol>');if(slider.pagingCount>1){for(var i=0;i<slider.pagingCount;i++){item=(vars.controlNav==="thumbnails")?'<img src="'+slider.slides.eq(i).attr("data-thumb")+'"/>':'<a>'+j+'</a>';slider.controlNavScaffold.append('<li>'+item+'</li>');j++;}}
(slider.controlsContainer)?$(slider.controlsContainer).append(slider.controlNavScaffold):slider.append(slider.controlNavScaffold);methods.controlNav.set();methods.controlNav.active();slider.controlNavScaffold.delegate('a, img',eventType,function(event){event.preventDefault();var $this=$(this),target=slider.controlNav.index($this);if(!$this.hasClass(namespace+'active')){slider.direction=(target>slider.currentSlide)?"next":"prev";slider.flexAnimate(target,vars.pauseOnAction);}});if(touch){slider.controlNavScaffold.delegate('a',"click touchstart",function(event){event.preventDefault();});}},setupManual:function(){slider.controlNav=slider.manualControls;methods.controlNav.active();slider.controlNav.live(eventType,function(event){event.preventDefault();var $this=$(this),target=slider.controlNav.index($this);if(!$this.hasClass(namespace+'active')){(target>slider.currentSlide)?slider.direction="next":slider.direction="prev";slider.flexAnimate(target,vars.pauseOnAction);}});if(touch){slider.controlNav.live("click touchstart",function(event){event.preventDefault();});}},set:function(){var selector=(vars.controlNav==="thumbnails")?'img':'a';slider.controlNav=$('.'+namespace+'control-nav li '+selector,(slider.controlsContainer)?slider.controlsContainer:slider);},active:function(){slider.controlNav.removeClass(namespace+"active").eq(slider.animatingTo).addClass(namespace+"active");},update:function(action,pos){if(slider.pagingCount>1&&action==="add"){slider.controlNavScaffold.append($('<li><a>'+slider.count+'</a></li>'));}else if(slider.pagingCount===1){slider.controlNavScaffold.find('li').remove();}else{slider.controlNav.eq(pos).closest('li').remove();}
methods.controlNav.set();(slider.pagingCount>1&&slider.pagingCount!==slider.controlNav.length)?slider.update(pos,action):methods.controlNav.active();}},directionNav:{setup:function(){var directionNavScaffold=$('<ul class="'+namespace+'direction-nav"><li><a class="'+namespace+'prev" href="#">'+vars.prevText+'</a></li><li><a class="'+namespace+'next" href="#">'+vars.nextText+'</a></li></ul>');if(slider.controlsContainer){$(slider.controlsContainer).append(directionNavScaffold);slider.directionNav=$('.'+namespace+'direction-nav li a',slider.controlsContainer);}else{slider.append(directionNavScaffold);slider.directionNav=$('.'+namespace+'direction-nav li a',slider);}
methods.directionNav.update();slider.directionNav.bind(eventType,function(event){event.preventDefault();var target=($(this).hasClass(namespace+'next'))?slider.getTarget('next'):slider.getTarget('prev');slider.flexAnimate(target,vars.pauseOnAction);});if(touch){slider.directionNav.bind("click touchstart",function(event){event.preventDefault();});}},update:function(){var disabledClass=namespace+'disabled';if(slider.pagingCount===1){slider.directionNav.addClass(disabledClass);}else if(!vars.animationLoop){if(slider.animatingTo===0){slider.directionNav.removeClass(disabledClass).filter('.'+namespace+"prev").addClass(disabledClass);}else if(slider.animatingTo===slider.last){slider.directionNav.removeClass(disabledClass).filter('.'+namespace+"next").addClass(disabledClass);}else{slider.directionNav.removeClass(disabledClass);}}else{slider.directionNav.removeClass(disabledClass);}}},pausePlay:{setup:function(){var pausePlayScaffold=$('<div class="'+namespace+'pauseplay"><a></a></div>');if(slider.controlsContainer){slider.controlsContainer.append(pausePlayScaffold);slider.pausePlay=$('.'+namespace+'pauseplay a',slider.controlsContainer);}else{slider.append(pausePlayScaffold);slider.pausePlay=$('.'+namespace+'pauseplay a',slider);}
methods.pausePlay.update((vars.slideshow)?namespace+'pause':namespace+'play');slider.pausePlay.bind(eventType,function(event){event.preventDefault();if($(this).hasClass(namespace+'pause')){slider.manualPause=true;slider.manualPlay=false;slider.pause();}else{slider.manualPause=false;slider.manualPlay=true;slider.play();}});if(touch){slider.pausePlay.bind("click touchstart",function(event){event.preventDefault();});}},update:function(state){(state==="play")?slider.pausePlay.removeClass(namespace+'pause').addClass(namespace+'play').text(vars.playText):slider.pausePlay.removeClass(namespace+'play').addClass(namespace+'pause').text(vars.pauseText);}},touch:function(){var startX,startY,offset,cwidth,dx,startT,scrolling=false;el.addEventListener('touchstart',onTouchStart,false);function onTouchStart(e){if(slider.animating){e.preventDefault();}else if(e.touches.length===1){slider.pause();cwidth=(vertical)?slider.h:slider.w;startT=Number(new Date());offset=(carousel&&reverse&&slider.animatingTo===slider.last)?0:(carousel&&reverse)?slider.limit-(((slider.itemW+vars.itemMargin)*slider.move)*slider.animatingTo):(carousel&&slider.currentSlide===slider.last)?slider.limit:(carousel)?((slider.itemW+vars.itemMargin)*slider.move)*slider.currentSlide:(reverse)?(slider.last-slider.currentSlide+slider.cloneOffset)*cwidth:(slider.currentSlide+slider.cloneOffset)*cwidth;startX=(vertical)?e.touches[0].pageY:e.touches[0].pageX;startY=(vertical)?e.touches[0].pageX:e.touches[0].pageY;el.addEventListener('touchmove',onTouchMove,false);el.addEventListener('touchend',onTouchEnd,false);}}
function onTouchMove(e){dx=(vertical)?startX-e.touches[0].pageY:startX-e.touches[0].pageX;scrolling=(vertical)?(Math.abs(dx)<Math.abs(e.touches[0].pageX-startY)):(Math.abs(dx)<Math.abs(e.touches[0].pageY-startY));if(!scrolling||Number(new Date())-startT>500){e.preventDefault();if(!fade&&slider.transitions){if(!vars.animationLoop){dx=dx/((slider.currentSlide===0&&dx<0||slider.currentSlide===slider.last&&dx>0)?(Math.abs(dx)/cwidth+2):1);}
slider.setProps(offset+dx,"setTouch");}}}
function onTouchEnd(e){el.removeEventListener('touchmove',onTouchMove,false);if(slider.animatingTo===slider.currentSlide&&!scrolling&&!(dx===null)){var updateDx=(reverse)?-dx:dx,target=(updateDx>0)?slider.getTarget('next'):slider.getTarget('prev');if(slider.canAdvance(target)&&(Number(new Date())-startT<550&&Math.abs(updateDx)>50||Math.abs(updateDx)>cwidth/2)){slider.flexAnimate(target,vars.pauseOnAction);}else{if(!fade)slider.flexAnimate(slider.currentSlide,vars.pauseOnAction,true);}}
el.removeEventListener('touchend',onTouchEnd,false);startX=null;startY=null;dx=null;offset=null;}},resize:function(){if(!slider.animating&&slider.is(':visible')){if(!carousel)slider.doMath();if(fade){methods.smoothHeight();}else if(carousel){slider.slides.width(slider.computedW);slider.update(slider.pagingCount);slider.setProps();}
else if(vertical){slider.viewport.height(slider.h);slider.setProps(slider.h,"setTotal");}else{if(vars.smoothHeight)methods.smoothHeight();slider.newSlides.width(slider.computedW);slider.setProps(slider.computedW,"setTotal");}}},smoothHeight:function(dur){if(!vertical||fade){var $obj=(fade)?slider:slider.viewport;(dur)?$obj.animate({"height":slider.slides.eq(slider.animatingTo).height()},dur):$obj.height(slider.slides.eq(slider.animatingTo).height());}},sync:function(action){var $obj=$(vars.sync).data("flexslider"),target=slider.animatingTo;switch(action){case"animate":$obj.flexAnimate(target,vars.pauseOnAction,false,true);break;case"play":if(!$obj.playing&&!$obj.asNav){$obj.play();}break;case"pause":$obj.pause();break;}}}
slider.flexAnimate=function(target,pause,override,withSync,fromNav){if(asNav&&slider.pagingCount===1)slider.direction=(slider.currentItem<target)?"next":"prev";if(!slider.animating&&(slider.canAdvance(target,fromNav)||override)&&slider.is(":visible")){if(asNav&&withSync){var master=$(vars.asNavFor).data('flexslider');slider.atEnd=target===0||target===slider.count-1;master.flexAnimate(target,true,false,true,fromNav);slider.direction=(slider.currentItem<target)?"next":"prev";master.direction=slider.direction;if(Math.ceil((target+1)/slider.visible)-1!==slider.currentSlide&&target!==0){slider.currentItem=target;slider.slides.removeClass(namespace+"active-slide").eq(target).addClass(namespace+"active-slide");target=Math.floor(target/slider.visible);}else{slider.currentItem=target;slider.slides.removeClass(namespace+"active-slide").eq(target).addClass(namespace+"active-slide");return false;}}
slider.animating=true;slider.animatingTo=target;vars.before(slider);if(pause)slider.pause();if(slider.syncExists&&!fromNav)methods.sync("animate");if(vars.controlNav)methods.controlNav.active();if(!carousel)slider.slides.removeClass(namespace+'active-slide').eq(target).addClass(namespace+'active-slide');slider.atEnd=target===0||target===slider.last;if(vars.directionNav)methods.directionNav.update();if(target===slider.last){vars.end(slider);if(!vars.animationLoop)slider.pause();}
if(!fade){var dimension=(vertical)?slider.slides.filter(':first').height():slider.computedW,margin,slideString,calcNext;if(carousel){margin=(vars.itemWidth>slider.w)?vars.itemMargin*2:vars.itemMargin;calcNext=((slider.itemW+margin)*slider.move)*slider.animatingTo;slideString=(calcNext>slider.limit&&slider.visible!==1)?slider.limit:calcNext;}else if(slider.currentSlide===0&&target===slider.count-1&&vars.animationLoop&&slider.direction!=="next"){slideString=(reverse)?(slider.count+slider.cloneOffset)*dimension:0;}else if(slider.currentSlide===slider.last&&target===0&&vars.animationLoop&&slider.direction!=="prev"){slideString=(reverse)?0:(slider.count+1)*dimension;}else{slideString=(reverse)?((slider.count-1)-target+slider.cloneOffset)*dimension:(target+slider.cloneOffset)*dimension;}
slider.setProps(slideString,"",vars.animationSpeed);if(slider.transitions){if(!vars.animationLoop||!slider.atEnd){slider.animating=false;slider.currentSlide=slider.animatingTo;}
slider.container.unbind("webkitTransitionEnd transitionend");slider.container.bind("webkitTransitionEnd transitionend",function(){slider.wrapup(dimension);});}else{slider.container.animate(slider.args,vars.animationSpeed,vars.easing,function(){slider.wrapup(dimension);});}}else{if(!touch){slider.slides.eq(slider.currentSlide).fadeOut(vars.animationSpeed,vars.easing);slider.slides.eq(target).fadeIn(vars.animationSpeed,vars.easing,slider.wrapup);}else{slider.slides.eq(slider.currentSlide).css({"opacity":0,"zIndex":1});slider.slides.eq(target).css({"opacity":1,"zIndex":2});slider.slides.unbind("webkitTransitionEnd transitionend");slider.slides.eq(slider.currentSlide).bind("webkitTransitionEnd transitionend",function(){vars.after(slider);});slider.animating=false;slider.currentSlide=slider.animatingTo;}}
if(vars.smoothHeight)methods.smoothHeight(vars.animationSpeed);}}
slider.wrapup=function(dimension){if(!fade&&!carousel){if(slider.currentSlide===0&&slider.animatingTo===slider.last&&vars.animationLoop){slider.setProps(dimension,"jumpEnd");}else if(slider.currentSlide===slider.last&&slider.animatingTo===0&&vars.animationLoop){slider.setProps(dimension,"jumpStart");}}
slider.animating=false;slider.currentSlide=slider.animatingTo;vars.after(slider);}
slider.animateSlides=function(){if(!slider.animating)slider.flexAnimate(slider.getTarget("next"));}
slider.pause=function(){clearInterval(slider.animatedSlides);slider.playing=false;if(vars.pausePlay)methods.pausePlay.update("play");if(slider.syncExists)methods.sync("pause");}
slider.play=function(){slider.animatedSlides=setInterval(slider.animateSlides,vars.slideshowSpeed);slider.playing=true;if(vars.pausePlay)methods.pausePlay.update("pause");if(slider.syncExists)methods.sync("play");}
slider.canAdvance=function(target,fromNav){var last=(asNav)?slider.pagingCount-1:slider.last;return(fromNav)?true:(asNav&&slider.currentItem===slider.count-1&&target===0&&slider.direction==="prev")?true:(asNav&&slider.currentItem===0&&target===slider.pagingCount-1&&slider.direction!=="next")?false:(target===slider.currentSlide&&!asNav)?false:(vars.animationLoop)?true:(slider.atEnd&&slider.currentSlide===0&&target===last&&slider.direction!=="next")?false:(slider.atEnd&&slider.currentSlide===last&&target===0&&slider.direction==="next")?false:true;}
slider.getTarget=function(dir){slider.direction=dir;if(dir==="next"){return(slider.currentSlide===slider.last)?0:slider.currentSlide+1;}else{return(slider.currentSlide===0)?slider.last:slider.currentSlide-1;}}
slider.setProps=function(pos,special,dur){var target=(function(){var posCheck=(pos)?pos:((slider.itemW+vars.itemMargin)*slider.move)*slider.animatingTo,posCalc=(function(){if(carousel){return(special==="setTouch")?pos:(reverse&&slider.animatingTo===slider.last)?0:(reverse)?slider.limit-(((slider.itemW+vars.itemMargin)*slider.move)*slider.animatingTo):(slider.animatingTo===slider.last)?slider.limit:posCheck;}else{switch(special){case"setTotal":return(reverse)?((slider.count-1)-slider.currentSlide+slider.cloneOffset)*pos:(slider.currentSlide+slider.cloneOffset)*pos;case"setTouch":return(reverse)?pos:pos;case"jumpEnd":return(reverse)?pos:slider.count*pos;case"jumpStart":return(reverse)?slider.count*pos:pos;default:return pos;}}}());return(posCalc*-1)+"px";}());if(slider.transitions){target=(vertical)?"translate3d(0,"+target+",0)":"translate3d("+target+",0,0)";dur=(dur!==undefined)?(dur/1000)+"s":"0s";slider.container.css("-"+slider.pfx+"-transition-duration",dur);}
slider.args[slider.prop]=target;if(slider.transitions||dur===undefined)slider.container.css(slider.args);}
slider.setup=function(type){if(!fade){var sliderOffset,arr;if(type==="init"){slider.viewport=$('<div class="'+namespace+'viewport"></div>').css({"overflow":"hidden","position":"relative"}).appendTo(slider).append(slider.container);slider.cloneCount=0;slider.cloneOffset=0;if(reverse){arr=$.makeArray(slider.slides).reverse();slider.slides=$(arr);slider.container.empty().append(slider.slides);}}
if(vars.animationLoop&&!carousel){slider.cloneCount=2;slider.cloneOffset=1;if(type!=="init")slider.container.find('.clone').remove();slider.container.append(slider.slides.first().clone().addClass('clone')).prepend(slider.slides.last().clone().addClass('clone'));}
slider.newSlides=$(vars.selector,slider);sliderOffset=(reverse)?slider.count-1-slider.currentSlide+slider.cloneOffset:slider.currentSlide+slider.cloneOffset;if(vertical&&!carousel){slider.container.height((slider.count+slider.cloneCount)*200+"%").css("position","absolute").width("100%");setTimeout(function(){slider.newSlides.css({"display":"block"});slider.doMath();slider.viewport.height(slider.h);slider.setProps(sliderOffset*slider.h,"init");},(type==="init")?100:0);}else{slider.container.width((slider.count+slider.cloneCount)*200+"%");slider.setProps(sliderOffset*slider.computedW,"init");setTimeout(function(){slider.doMath();slider.newSlides.css({"width":slider.computedW,"float":"left","display":"block"});if(vars.smoothHeight)methods.smoothHeight();},(type==="init")?100:0);}}else{slider.slides.css({"width":"100%","float":"left","marginRight":"-100%","position":"relative"});if(type==="init"){if(!touch){slider.slides.eq(slider.currentSlide).fadeIn(vars.animationSpeed,vars.easing);}else{slider.slides.css({"opacity":0,"display":"block","webkitTransition":"opacity "+vars.animationSpeed/1000+"s ease","zIndex":1}).eq(slider.currentSlide).css({"opacity":1,"zIndex":2});}}
if(vars.smoothHeight)methods.smoothHeight();}
if(!carousel)slider.slides.removeClass(namespace+"active-slide").eq(slider.currentSlide).addClass(namespace+"active-slide");}
slider.doMath=function(){var slide=slider.slides.first(),slideMargin=vars.itemMargin,minItems=vars.minItems,maxItems=vars.maxItems;slider.w=slider.width();slider.h=slide.height();slider.boxPadding=slide.outerWidth()-slide.width();if(carousel){slider.itemT=vars.itemWidth+slideMargin;slider.minW=(minItems)?minItems*slider.itemT:slider.w;slider.maxW=(maxItems)?maxItems*slider.itemT:slider.w;slider.itemW=(slider.minW>slider.w)?(slider.w-(slideMargin*minItems))/minItems:(slider.maxW<slider.w)?(slider.w-(slideMargin*maxItems))/maxItems:(vars.itemWidth>slider.w)?slider.w:vars.itemWidth;slider.visible=Math.floor(slider.w/(slider.itemW+slideMargin));slider.move=(vars.move>0&&vars.move<slider.visible)?vars.move:slider.visible;slider.pagingCount=Math.ceil(((slider.count-slider.visible)/slider.move)+1);slider.last=slider.pagingCount-1;slider.limit=(slider.pagingCount===1)?0:(vars.itemWidth>slider.w)?((slider.itemW+(slideMargin*2))*slider.count)-slider.w-slideMargin:((slider.itemW+slideMargin)*slider.count)-slider.w-slideMargin;}else{slider.itemW=slider.w;slider.pagingCount=slider.count;slider.last=slider.count-1;}
slider.computedW=slider.itemW-slider.boxPadding;}
slider.update=function(pos,action){slider.doMath();if(!carousel){if(pos<slider.currentSlide){slider.currentSlide+=1;}else if(pos<=slider.currentSlide&&pos!==0){slider.currentSlide-=1;}
slider.animatingTo=slider.currentSlide;}
if(vars.controlNav&&!slider.manualControls){if((action==="add"&&!carousel)||slider.pagingCount>slider.controlNav.length){methods.controlNav.update("add");}else if((action==="remove"&&!carousel)||slider.pagingCount<slider.controlNav.length){if(carousel&&slider.currentSlide>slider.last){slider.currentSlide-=1;slider.animatingTo-=1;}
methods.controlNav.update("remove",slider.last);}}
if(vars.directionNav)methods.directionNav.update();}
slider.addSlide=function(obj,pos){var $obj=$(obj);slider.count+=1;slider.last=slider.count-1;if(vertical&&reverse){(pos!==undefined)?slider.slides.eq(slider.count-pos).after($obj):slider.container.prepend($obj);}else{(pos!==undefined)?slider.slides.eq(pos).before($obj):slider.container.append($obj);}
slider.update(pos,"add");slider.slides=$(vars.selector+':not(.clone)',slider);slider.setup();vars.added(slider);}
slider.removeSlide=function(obj){var pos=(isNaN(obj))?slider.slides.index($(obj)):obj;slider.count-=1;slider.last=slider.count-1;if(isNaN(obj)){$(obj,slider.slides).remove();}else{(vertical&&reverse)?slider.slides.eq(slider.last).remove():slider.slides.eq(obj).remove();}
slider.doMath();slider.update(pos,"remove");slider.slides=$(vars.selector+':not(.clone)',slider);slider.setup();vars.removed(slider);}
methods.init();}
$.flexslider.defaults={namespace:"flex-",selector:".slides > li",animation:"fade",easing:"swing",direction:"horizontal",reverse:false,animationLoop:true,smoothHeight:false,startAt:0,slideshow:false,slideshowSpeed:7000,animationSpeed:600,initDelay:0,randomize:false,pauseOnAction:false,pauseOnHover:false,useCSS:true,touch:true,video:false,controlNav:false,directionNav:true,prevText:"&#8592",nextText:" &#8594",keyboard:true,multipleKeyboard:true,mousewheel:false,pausePlay:false,pauseText:"Pause",playText:"Play",controlsContainer:"",manualControls:"",sync:"",asNavFor:"",itemWidth:0,itemMargin:0,minItems:0,maxItems:0,move:0,start:function(){},before:function(){},after:function(){},end:function(){},added:function(){},removed:function(){}}
$.fn.flexslider=function(options){if(options===undefined)options={};if(typeof options==="object"){return this.each(function(){var $this=$(this),selector=(options.selector)?options.selector:".slides > li",$slides=$this.find(selector);if($slides.length===1){$slides.fadeIn(400);if(options.start)options.start($this);}else if($this.data('flexslider')==undefined){new $.flexslider(this,options);}});}else{var $slider=$(this).data('flexslider');switch(options){case"play":$slider.play();break;case"pause":$slider.pause();break;case"next":$slider.flexAnimate($slider.getTarget("next"),true);break;case"prev":case"previous":$slider.flexAnimate($slider.getTarget("prev"),true);break;default:if(typeof options==="number")$slider.flexAnimate(options,true);}}}})(jQuery);$(window).load(function(){$('.flexslider').flexslider({});});
//Tabs
var RESPONSIVEUI={};(function($){RESPONSIVEUI.responsiveTabs=function(){var $tabSets=$('.responsive-tabs');if(!$tabSets.hasClass('responsive-tabs--enabled')){$tabSets.addClass('responsive-tabs--enabled');var tablistcount=1;$tabSets.each(function(){var $tabs=$(this);$tabs.children(':header').addClass('responsive-tabs__heading');$tabs.children('div').addClass('responsive-tabs__panel');var $activePanel=$tabs.find('.responsive-tabs__panel--active');if(!$activePanel.length){$activePanel=$tabs.find('.responsive-tabs__panel').first().addClass('responsive-tabs__panel--active');}
$tabs.find('.responsive-tabs__panel').not('.responsive-tabs__panel--active').hide().attr('aria-hidden','true');$activePanel.attr('aria-hidden','false');$activePanel.addClass('responsive-tabs__panel--closed-accordion-only');var $tabsWrapper=$('<div/>',{'class':'responsive-tabs-wrapper'});$tabs.wrap($tabsWrapper);var highestHeight=0;$tabs.find('.responsive-tabs__panel').each(function(){var tabHeight=$(this).height();if(tabHeight>highestHeight){highestHeight=tabHeight;}});var $tabList=$('<ul/>',{'class':'responsive-tabs__list','role':'tablist'});var tabcount=1;$tabs.find('.responsive-tabs__heading').each(function(){var $tabHeading=$(this);var $tabPanel=$(this).next();$tabHeading.attr('tabindex',0);var $tabListItem=$('<li/>',{'class':'responsive-tabs__list__item',id:'tablist'+tablistcount+'-tab'+tabcount,'aria-controls':'tablist'+tablistcount+'-panel'+tabcount,'role':'tab',tabindex:0,text:$tabHeading.text(),keydown:function(objEvent){if(objEvent.keyCode===13){$tabListItem.click();}},click:function(){$tabsWrapper.css('height',highestHeight);$tabs.find('.responsive-tabs__panel--closed-accordion-only').removeClass('responsive-tabs__panel--closed-accordion-only');$tabs.find('.responsive-tabs__panel--active').toggle().removeClass('responsive-tabs__panel--active').attr('aria-hidden','true').prev().removeClass('responsive-tabs__heading--active');$tabPanel.toggle().addClass('responsive-tabs__panel--active').attr('aria-hidden','false');$tabHeading.addClass('responsive-tabs__heading--active');$tabList.find('.responsive-tabs__list__item--active').removeClass('responsive-tabs__list__item--active');$tabListItem.addClass('responsive-tabs__list__item--active');$tabsWrapper.css('height','auto');}});$tabPanel.attr({'role':'tabpanel','aria-labelledby':$tabListItem.attr('id'),id:'tablist'+tablistcount+'-panel'+tabcount});if($tabPanel.hasClass('responsive-tabs__panel--active')){$tabListItem.addClass('responsive-tabs__list__item--active');}
$tabList.append($tabListItem);$tabHeading.keydown(function(objEvent){if(objEvent.keyCode===13){$tabHeading.click();}});$tabHeading.click(function(){$tabs.find('.responsive-tabs__panel--closed-accordion-only').removeClass('responsive-tabs__panel--closed-accordion-only');if(!$tabHeading.hasClass('responsive-tabs__heading--active')){var oldActivePos,$activeHeading=$tabs.find('.responsive-tabs__heading--active');if($activeHeading.length){oldActivePos=$activeHeading.offset().top;}
$tabs.find('.responsive-tabs__panel--active').slideToggle().removeClass('responsive-tabs__panel--active').prev().removeClass('responsive-tabs__heading--active');$tabs.find('.responsive-tabs__panel').hide().attr('aria-hidden','true');$tabPanel.slideToggle().addClass('responsive-tabs__panel--active').attr('aria-hidden','false');$tabHeading.addClass('responsive-tabs__heading--active');var $currentActive=$tabs.find('.responsive-tabs__list__item--active');$currentActive.removeClass('responsive-tabs__list__item--active');var panelId=$tabPanel.attr('id');var tabId=panelId.replace('panel','tab');$('#'+tabId).addClass('responsive-tabs__list__item--active');var tabsPos=$tabs.offset().top;var newActivePos=($tabHeading.offset().top)-15;if(oldActivePos<newActivePos){$('html, body').animate({scrollTop:tabsPos},0).animate({scrollTop:newActivePos},400);}}
else{$tabPanel.removeClass('responsive-tabs__panel--active').slideToggle(function(){$(this).addClass('responsive-tabs__panel--closed-accordion-only');});$tabHeading.removeClass('responsive-tabs__heading--active');}});tabcount++;});$tabs.prepend($tabList);tablistcount++;});}};})(jQuery);$(document).ready(function(){RESPONSIVEUI.responsiveTabs();})
//Haiku na denot
$(document).ready(function(){
var todays_obj=new Date();
var todays_date=todays_obj.getDate();

var haiku=new Array();

haiku[0]="Снегот ги освои<br>Сите полиња... брегови...<br>Не остави ништо.<br><span>Наито Џосо</span>";
haiku[1]="Зимски облаци.<br>Гавранот по трет пат го<br>фрла орeвот.<br><span>Александар Маџаровски</span>";
haiku[2]="Врз гола гранка<br>седи осамен гавран.<br>Есенска вечер.<br><span>Мацуо Башо</span>";
haiku[3]="Паѓаат ѕвезди.<br>Си замислив желба -<br>да паднат на меко.<br><span>Никола Маџиров</span>";
haiku[4]="Месечино над сртот,<br>Осветли го, те колнам,<br>оној што краде цвеќе!<br><span>Кобајаши Иса</span>";
haiku[5]="Дождот веселник<br>му ја симна шапката<br>на глуварчето.<br><span>Цане Андреевски</span>";
haiku[6]="Сув лист<br>лета назад кон гранката.<br>Не, тоа е пеперутка.<br><span>Аракида Моритаке</span>";
haiku[7]="пред колибата оган<br>внатре ореви и черги<br>лежиме и ги чуваме ѕвездите<br><span>Христо Петрески</span>";
haiku[8]="Ги собори и<br>последните лисја.<br>Есента во нас.<br><span>Тони Попов</span>";
haiku[9]="<b>Прошка</b><br>Стапнав цвет, а тој<br>со мириси го бакна<br>тоа злосторство.<br><span>Теа Конеска</span>";
haiku[10]="Зимско утро<br>Од брезата врапци<br>ми тресат снег во тилот ...<br><span>Петко Дабески</span>";
haiku[11]="Пеперутката<br>Се зажеле за дома<br>Здогледа нов цвет<br><span>Марија Дачевска</span>";
haiku[12]="Додадете дршка<br>на месечината:<br>прекрасно ладало!<br><span>Јамазаки Сокан</span>";
haiku[13]="Дрва за огрев<br>сечат... а кој ќе ги<br>згрее птиците?<br><span>Искра Донева</span>";
haiku[14]="Дома се враќам,<br>Но сега по друга патека -<br>заради темјанушките<br><span>Хота Бакусуи</span>";
haiku[15]="Скришно без врева<br>цутат скопските липи<br>секогаш ноќе.<br><span>Живко Новески</span>";
haiku[16]="Црешовите цветови<br>се распослаа пак врз мене<br>додека дремев<br><span>Муечика Оницура</span>";
haiku[17]="сончево утро -<br>на жица штипката држи<br>две капки роса<br><span>Димиар Аргакијев</span>";
haiku[18]="Црешовиот цвет<br>го натера и благородникот<br>да слезе од коњот<br><span>Кобајаши Иса</span>";
haiku[19]="Мирис на липи...<br>Градот станал шишенце<br>полно со парфем!<br><span>Дејан Василевски</span>";
haiku[20]="Сликам темјанушка.<br>Само за мирисот нејзин<br>ми недостасува боја.<br><span>Видое Подгорец</span>";
haiku[21]="Поглед кон запад.<br>Далеку е мојот дом<br>му шепнав на чајот.<br><span>Даниела Јосифова</span>";
haiku[22]="\„Ене светулки!\“<br>Ќе извикав за малку.<br>Но бев сам.<br><span>Тан Таиги</span>";
haiku[23]="Скинав капинка<br>трнчиња на прстите<br>крв на усните<br><span>Владо Јоциќ</span>";
haiku[24]="Во моето старо село<br>од година на година<br>црешата сè помалку цути.<br><span>Собаку</span>";
haiku[25]="Пливаме грбно -<br>ние во морето, а<br>облакот на небо.<br><span>Владимир Мартиновски</span>";
haiku[26]="Мравја патека.<br>Од врвовите на облаците<br>се спушта.<br><span>Кобајаши Иса</span>";
haiku[27]="Пет ноќи празен<br>домот остарел за цела<br>една година.<br><span>Александар Прокопиев</span>";
haiku[28]="Бисерни капки.<br>Како да се нижат од<br>тревка до тревка.<br><span>Хатори Рансецу</span>";
haiku[29]="Одам по јаже.<br>Скинато и фрлено<br>покрај циркусот.<br><span>Александар Кујунџиски</span>";
haiku[30]="Најпрвин ги<br>урна сите страшила -<br>есенски ветар.<br><span>Морикава Киороку</span>";




//Last haiku
lasthaiku = 30;

var whichhaiku=todays_date;

//whichhaiku=Math.floor(Math.random()*(haiku.length))

if (whichhaiku > lasthaiku) {
			whichhaiku=lasthaiku;
};
	$('.haiku-doma').append('<div>' + haiku [whichhaiku] + '</div>');
});
// Collapser
(function($){
    $.fn.collapser= function(options, beforeCallback, afterCallback) {
        
        var defaults = {
            target: 'next',
			targetOnly: null,
            effect: 'slide',
			changeText: true,
			expandHtml: '[+]',
			collapseHtml: '[-]',
			expandClass: '',
			collapseClass:''
        };
        
        var options = $.extend(defaults, options);
		
		var expHtml,collHtml, effectShow, effectHide;
		
		if(options.effect == 'slide'){
			effectShow = 'slideDown';
			effectHide = 'slideUp';
		}else{
			effectShow = 'fadeIn';
			effectHide = 'fadeOut';
		}
		
		if(options.changeText == true){
			expHtml = options.expandHtml;
			collHtml = options.collapseHtml;
		}
		
		function callBeforeCallback(obj){
			if(beforeCallback !== undefined){
				beforeCallback.apply(obj);
			}
		}
		
		function callAfterCallback(obj){
			if(afterCallback !== undefined){
				afterCallback.apply(obj);
			}
		}
		
		function hideElement(obj, method){
			callBeforeCallback(obj);
			if(method == 1){
				obj[options.target](options.targetOnly)[effectHide]();
				obj.html(expHtml);
				obj.removeClass(options.collapseClass);
				obj.addClass(options.expandClass);
			}else{
				$(document).find(options.target)[effectHide]();
				obj.html(expHtml);
				obj.removeClass(options.collapseClass);
				obj.addClass(options.expandClass);
			}
			callAfterCallback(obj);
		}
		
		function showElement(obj, method){
			callBeforeCallback(obj)
			if(method == 1){
				obj[options.target](options.targetOnly)[effectShow]();
				obj.html(collHtml);
				obj.removeClass(options.expandClass);
				obj.addClass(options.collapseClass);
			}else{
				$(document).find(options.target)[effectShow]();
				obj.html(collHtml);
				obj.removeClass(options.expandClass);
				obj.addClass(options.collapseClass);
			}
			callAfterCallback(obj);
		}
		
		function toggleElement(obj, method){
			if(method == 1){
				if(obj[options.target](options.targetOnly).is(':visible')){
					hideElement(obj, 1);
				}else{
					showElement(obj, 1);
				}
			}else{
				if($(document).find(options.target).is(':visible')){
					hideElement(obj, 2);
				}else{
					showElement(obj, 2);
				}
			}
		}
		
		return this.each(function(){
		   
		   if($.fn[options.target] && $(this)[options.target]()){
				$(this).toggle(function(){		
					toggleElement($(this), 1);
				},function(){
					toggleElement($(this), 1);
				});	
				
		   }else{
			   
			   $(this).toggle(function(){
					toggleElement($(this), 2);
				},function(){
					toggleElement($(this), 2);
				});
		   }
		   
		   // Initialize  
		   if($.fn[options.target] && $(this)[options.target]()){
				if($(this)[options.target]().is(':hidden')){
					$(this).html(expHtml);
					$(this).removeClass(options.collapseClass);
					$(this).addClass(options.expandClass);
				}else{
					$(this).html(collHtml);
					$(this).removeClass(options.expandClass);
					$(this).addClass(options.collapseClass);
				}
			}else{
				if($(document).find(options.target).is(':hidden')){
					$(this).html(expHtml);
				}else{
					$(this).html(collHtml);
				}
			}
		   
        });
    };
    
})(jQuery);$('.p1, .p2, .p3, .p4, .p5').collapser({ targetOnly:'div' });
